### ISSUE TITLE
Getting different query results than in blog post - parse_json() issue?

### ISSUE THREAD

**Issue by thebleucheese** [OTRF/Microsoft-Sentinel2Go#21]
Hey thanks for creating this, it's awesome.

I manually setup an ELK stack with Mordor data a year or so ago and it took me quite a few hours to get it working. This was up and running in a few minutes after reading the docs.  

One area where I'm stuck is I'm getting different results than in the blog post here: https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/azure-sentinel-to-go-part1-a-lab-w-prerecorded-data-amp-a-custom/ba-p/1260191

I run the following command:
`prerecorded_CL
| extend m=parse_json(Message)
| summarize count() by EventID=tostring(m.winlog.event_id),EventProvider=tostring(m.winlog.channel),Task=tostring(m.winlog.task)`

And my results are as follows:
![sentinelQuery](https://user-images.githubusercontent.com/30511683/154867171-64f51fba-bff8-4413-9b28-c2fe2b82de80.png)

I can tell I have the mordor data present:
![mordorDataPresent](https://user-images.githubusercontent.com/30511683/154867235-3afc3f95-36d2-4e46-b4ce-0c52aef838f2.png)

But for some reason it looks like parse_json() isn't working the same way on the Message field, or maybe I'm not executing the query properly. I'm used to Kibana KQL. I feel like I'm just doing something dumb or missing a step. Any ideas?

Edit: And I guess as a follow-up, when I imported these datasets into ELK I did some work to have them parsed and saved in Elastic Common Schema, ECS.  I know you worked on OSSEM and It looks like MS has a similar set of common schema formats defined in ASIM here: https://docs.microsoft.com/en-us/azure/sentinel/normalization  Have you used any parsers in the log ingest pipeline to get this into a common schema so that we don't need to worry about the 500 custom field limit or the parse_json() calls in the queries?

**Comment by Cyb3rWard0g** [comment]
Hello @thebleucheese ! Thank you for letting me know regarding the query in the blog post. I believe that was parsing some of the old logs we captured in the "SecurityDatasets" project (formerly known as Mordor). I believe if you can show one event `prerecorded_CL | extend m=parse_json(Message) |  Limit 1` and share it here, I believe we can get to the specific field we need to `summary count() by`. The `*.winlog.*` is old.

**Comment by Cyb3rWard0g** [comment]
Regarding parsers to normalize events. I do not think it works in `custom` tables (i.e. `prerecorded_CL`). The ASIM parsers are used at query-time and they are used as any other KQL function. https://github.com/Azure/Azure-Sentinel/tree/master/ASIM

**Comment by thebleucheese** [comment]
You got me on the right track, this worked: 

`prerecorded_CL 
    | extend m=parse_json(Message) 
    | summarize count() by 
        EventID=tostring(m.EventID),
        EventProvider=tostring(m.Channel),
        Task=tostring(m.Task)`

In response to normalization, thanks I see that now here in the architecture diagram - https://docs.microsoft.com/en-us/azure/sentinel/normalization. I didn't initially realize the parsing step was at query time. I thought it might be persisted.
