### ISSUE TITLE
Error during deployment validation

### ISSUE THREAD

**Issue by Zhuich** [OTRF/Microsoft-Sentinel2Go#22]
Deployment template validation failed: 'The template resource 'Microsoft.Resources/deployments/deployVnetPeering' reference to 'Microsoft.Resources/deployments/deployC2' requires an API version. Please see https://aka.ms/arm-template for usage details.'.

**Comment by Cyb3rWard0g** [comment]
Hello @Zhuich ! mmm which template were you using in this scenario?

**Comment by Cyb3rWard0g** [comment]
Ahh I think I found the issue. Pushing a fix for it in a few minutes. Thank you for your patience!

**Comment by Cyb3rWard0g** [comment]
That worked for me! Thank you @Zhuich !

Feel free to reopen the issue if you still have problems with it. Thank you for letting me know.
