### ISSUE TITLE
Workspace Region parameter error message

### ISSUE THREAD

**Issue by jagjag6** [OTRF/Microsoft-Sentinel2Go#24]
Hi Sentinel2Go team

Thank you for this very useful project, I appreciate it.

Two weeks ago I was able to successfully deploy the Win10-AD-WEC template
https://github.com/OTRF/Microsoft-Sentinel2Go/tree/master/grocery-list/Win10-AD-WEC

Today I have tried again and I get the following validation failure
{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template parameters 'Workspace Region' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'Workspace, WorkspaceRegion'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'."}

Am I doing something wrong? I'm using the same Azure account as a few weeks ago.  Do you need any other information? Thanks

Jag

**Comment by Cyb3rWard0g** [comment]
Hello @jagjag6 !

That variable looks familiar and I believe it comes from ASIM templates . Taking a look at it

**Comment by Cyb3rWard0g** [comment]
Found the issue and it is the ASIM templates managed by the Azure Sentinel team in their official repository.

## Microsoft-Sentinel To-Go - Windows AD WEC Template

Every Windows template in this project now uses ASIM ARM templates to deploy KQL parsers to standardize Windows security and Windows Sysmon events. 

In our template, we define variables to manage what parsers to deploy:

https://github.com/OTRF/Microsoft-Sentinel2Go/blob/master/grocery-list/Win10-AD-WEC/azuredeploy.json#L222-L224

This gets used in this resource to call an external template that we developed to deploy KQL functions/parsers:

https://github.com/OTRF/Microsoft-Sentinel2Go/blob/master/grocery-list/Win10-AD-WEC/azuredeploy.json#L230-L258

## Microsoft Sentinel To-Go - Functions Template

This is the template we use to call 2 external templates available in the Azure Sentinel repository:

https://github.com/OTRF/Microsoft-Sentinel2Go/blob/master/microsoft-sentinel/linkedtemplates/log-analytics/functions.json#L27-L28

* **Windows Template**: https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASim%20WindowsEvent/ARM/MicrosoftWindowsEventFullDeployment.json
* **Sysmon Template**: https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASim%20Sysmon%20for%20Windows/SysmonFullDeployment.json

## Azure Sentinel Repository - MicrosoftWindowsEventFullDeployment Template
        
This template deploys other templates that are also part of the Azure Sentinel repo.

https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASim%20WindowsEvent/ARM/MicrosoftWindowsEventFullDeployment.json

### 🚨 🚨  THE ISSUE - linkedASimNetworkSessionMicrosoftWindowsEventFirewall Deployment Parameter

The last resource in the `MicrosoftWindowsEventFullDeployment` template deploys another template:

https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASim%20WindowsEvent/ARM/MicrosoftWindowsEventFullDeployment.json#L95-L113

that deployment resource uses the input parameter `Workspace Region`

https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASim%20WindowsEvent/ARM/MicrosoftWindowsEventFullDeployment.json#L108

## Azure Sentinel Repository - ASimNetworkSessionMicrosoftWindowsEventFirewall Template

However, if we go to the template `ASimNetworkSessionMicrosoftWindowsEventFirewall` 

https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimNetworkSession/ARM/ASimNetworkSessionMicrosoftWindowsEventFirewall/ASimNetworkSessionMicrosoftWindowsEventFirewall.json

You can see that it does not have a `Workspace Region` parameter. it has a `WorkspaceRegion` parameter:

https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimNetworkSession/ARM/ASimNetworkSessionMicrosoftWindowsEventFirewall/ASimNetworkSessionMicrosoftWindowsEventFirewall.json#L11

**Comment by Cyb3rWard0g** [comment]
5 days ago (Today is May 7th, 2022), this happened:

**Comment by Cyb3rWard0g** [comment]
Created issue in Azure Sentinel repo: https://github.com/Azure/Azure-Sentinel/issues/4823

**Comment by Cyb3rWard0g** [comment]
Created PR in Azure-Sentinel repo: https://github.com/Azure/Azure-Sentinel/pull/4824

For now, this project is using the following link while calling the `MicrosoftWindowsEventFullDeployment` template from our templates:

https://github.com/Cyb3rWard0g/Azure-Sentinel/blob/master/Parsers/ASim%20WindowsEvent/ARM/MicrosoftWindowsEventFullDeployment.json

The parameter is updated:

https://github.com/Cyb3rWard0g/Azure-Sentinel/blob/master/Parsers/ASim%20WindowsEvent/ARM/MicrosoftWindowsEventFullDeployment.json#L108

**Comment by Cyb3rWard0g** [comment]
Thank you for the heads up @jagjag6 ! :)

**Comment by jagjag6** [comment]
Thank you @Cyb3rWard0g 
I can confirm what you have done has fixed this. I'm using s2g right now! Many thanks
